### PR TITLE
Fixed JS file name in `NestedModelAdmin`.  Also ...

### PR DESCRIPTION
**Pull request by christianpbrink**
... made definition of `deleted_forms` safer in `get_form`.

### CODE REVIEW

**Comment by geralddejong** [comment]
Is this not going to be merged?  I'm having to use Christian's fork.

**Comment by allanjamesvestal** [comment]
Merged. Not sure if it's just the `admin.py` config I looked at (which also has non-nested inlines), but `inlines.js` seems to be imported already. Apologies for the delay.

I'll do some more investigating, but can either of you confirm that this isn't necessarily a redundant include?

**Comment by christianpbrink** [comment]
I won't have time in the next few weeks to look into whether it's redundant.

**Comment by allanjamesvestal** [comment]
OK. I'll just make a sample admin config without any other inlines (besides both levels of nested ones), and see if the file's still being imported across all permutations (nested and stacked).

Probably going to do that tomorrow or the next day; evaluating and incorporating more recent commits from Soaa-'s django.contrib.admin at the moment.

Thanks for the fix!

**Pull request merged**
